# Generated by Django 5.2.7 on 2025-10-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('username', models.CharField(max_length=100, unique=True)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('started', models.BooleanField(default=True)),
            ],
        ),
    ]
