# Generated by Django 5.2.7 on 2025-10-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='code',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
