# Generated by Django 5.2.7 on 2025-10-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_alter_roommodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
