# Generated by Django 5.2.7 on 2025-11-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0003_alter_roommodel_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='started',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
