# Generated by Django 5.2.8 on 2025-12-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0004_alter_roommodel_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
