# Generated by Django 5.2.8 on 2025-12-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0005_roommodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='status',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=15),
        ),
    ]
