# Generated by Django 5.2.7 on 2025-11-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Players', '0005_remove_playermodel_status_playermodel_is_mafia'),
        ('Rooms', '0004_alter_roommodel_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('round_number', models.IntegerField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='Rooms.roommodel')),
                ('votee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='Players.playermodel')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='Players.playermodel')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'round_number'], name='vote_votemo_room_id_838250_idx')],
                'unique_together': {('room', 'voter', 'round_number')},
            },
        ),
    ]
