# Generated by Django 5.2.7 on 2025-11-29 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0004_alter_roommodel_started'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='Rooms.roommodel')),
            ],
        ),
        migrations.DeleteModel(
            name='VoteModel',
        ),
    ]
