# Generated by Django 5.2.8 on 2025-12-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_messagemodel_delete_votemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='message',
            field=models.TextField(),
        ),
    ]
