# Generated by Django 5.2.7 on 2025-11-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0002_playermodel_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
