# Generated by Django 5.2.8 on 2025-12-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0005_remove_playermodel_status_playermodel_is_mafia'),
        ('Rooms', '0006_alter_roommodel_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playermodel',
            index=models.Index(fields=['room', 'online'], name='Players_pla_room_id_485910_idx'),
        ),
    ]
