# Generated by Django 5.2.7 on 2025-11-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
