# Generated by Django 5.2.7 on 2025-11-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0003_playermodel_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermodel',
            old_name='isAdmin',
            new_name='is_admin',
        ),
    ]
