# Generated by Django 5.2.7 on 2025-11-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0004_rename_isadmin_playermodel_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermodel',
            name='status',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='is_mafia',
            field=models.BooleanField(default=False),
        ),
    ]
